import type {
  School,
  Claim,
  Signal,
  Issue,
  TimelineEvent,
  WeeklyReview,
  MemoryEvent,
  PulseQuestion,
  AttendanceRecord,
  TrendPoint,
} from "./types"

export const DISTRICT = {
  name: "Sitapur District",
  total: 487,
  stable: 312,
  watch: 121,
  attention: 39,
  escalated: 15,
}

export const schools: School[] = [
  {
    id: "sch-a",
    name: "Govt Primary School, Rampur",
    udise: "09250100304",
    block: "Biswan",
    cluster: "Rampur Cluster",
    district: "Sitapur",
    students: 184,
    teachers: 6,
    status: "escalated",
    attendanceReported: 96,
    attendanceObserved: 82,
    openIssues: 4,
    escalations: 1,
    lastSignalDaysAgo: 0,
  },
  {
    id: "sch-b",
    name: "Govt Upper Primary, Mahmudabad",
    udise: "09250100712",
    block: "Mahmudabad",
    cluster: "Central Cluster",
    district: "Sitapur",
    students: 312,
    teachers: 11,
    status: "attention",
    attendanceReported: 91,
    attendanceObserved: 85,
    openIssues: 3,
    escalations: 0,
    lastSignalDaysAgo: 1,
  },
  {
    id: "sch-c",
    name: "Govt Girls School, Laharpur",
    udise: "09250100155",
    block: "Laharpur",
    cluster: "North Cluster",
    district: "Sitapur",
    students: 268,
    teachers: 9,
    status: "watch",
    attendanceReported: 93,
    attendanceObserved: 90,
    openIssues: 2,
    escalations: 0,
    lastSignalDaysAgo: 1,
  },
  {
    id: "sch-d",
    name: "Govt Primary School, Sidhauli",
    udise: "09250100489",
    block: "Sidhauli",
    cluster: "South Cluster",
    district: "Sitapur",
    students: 142,
    teachers: 5,
    status: "stable",
    attendanceReported: 94,
    attendanceObserved: 93,
    openIssues: 1,
    escalations: 0,
    lastSignalDaysAgo: 0,
  },
  {
    id: "sch-e",
    name: "Govt Upper Primary, Reusa",
    udise: "09250100901",
    block: "Reusa",
    cluster: "East Cluster",
    district: "Sitapur",
    students: 205,
    teachers: 8,
    status: "watch",
    attendanceReported: 89,
    attendanceObserved: 84,
    openIssues: 2,
    escalations: 0,
    lastSignalDaysAgo: 3,
  },
  {
    id: "sch-f",
    name: "Govt Primary School, Khairabad",
    udise: "09250100623",
    block: "Khairabad",
    cluster: "West Cluster",
    district: "Sitapur",
    students: 176,
    teachers: 6,
    status: "stable",
    attendanceReported: 92,
    attendanceObserved: 91,
    openIssues: 0,
    escalations: 0,
    lastSignalDaysAgo: 0,
  },
]

export const FOCUS_SCHOOL_ID = "sch-a"

export const claims: Claim[] = [
  {
    id: "clm-water",
    schoolId: "sch-a",
    domain: "Infrastructure",
    subject: "Drinking Water",
    predicate: "Available to students",
    timeScope: "This week",
    reportedState: "Yes — functional",
    observedState: "Likely No",
    verifiedState: "Failure confirmed",
    confidence: "high",
    realityGap: "persistent",
    lastUpdated: "2h ago",
    recommendation: "Escalation threshold reached — block-level support required.",
  },
  {
    id: "clm-attendance",
    schoolId: "sch-a",
    domain: "Students",
    subject: "Attendance",
    predicate: "Matches independent evidence",
    timeScope: "Today",
    reportedState: "96% present",
    observedState: "~82% present",
    verifiedState: "Unknown",
    confidence: "medium",
    realityGap: "persistent",
    lastUpdated: "4h ago",
    recommendation: "Request clarification from teacher. Do not assume misconduct.",
  },
  {
    id: "clm-meal",
    schoolId: "sch-a",
    domain: "Nutrition",
    subject: "Midday Meal",
    predicate: "Served today",
    timeScope: "Today",
    reportedState: "Yes",
    observedState: "Yes",
    verifiedState: "Yes",
    confidence: "high",
    realityGap: "none",
    lastUpdated: "3h ago",
  },
  {
    id: "clm-lab",
    schoolId: "sch-a",
    domain: "Resources",
    subject: "Computer Lab",
    predicate: "Functional & in use",
    timeScope: "This month",
    reportedState: "Yes",
    observedState: "No activity 31 days",
    verifiedState: "Unknown",
    confidence: "low",
    realityGap: "verify",
    lastUpdated: "1d ago",
    recommendation: "Request verification — last inspection 8 months ago.",
  },
  {
    id: "clm-toilet",
    schoolId: "sch-a",
    domain: "Infrastructure",
    subject: "Girls' Toilet",
    predicate: "Usable",
    timeScope: "This week",
    reportedState: "Usable",
    observedState: "Door broken",
    verifiedState: "Under review",
    confidence: "medium",
    realityGap: "significant",
    lastUpdated: "6h ago",
    recommendation: "Local maintenance dependency — monitor resolution.",
  },
  {
    id: "clm-teacher",
    schoolId: "sch-a",
    domain: "Staff",
    subject: "Class Delivery",
    predicate: "Scheduled classes conducted",
    timeScope: "This week",
    reportedState: "All conducted",
    observedState: "Mostly conducted",
    verifiedState: "Likely",
    confidence: "medium",
    realityGap: "minor",
    lastUpdated: "5h ago",
  },
]

export const signals: Signal[] = [
  {
    id: "sig-1",
    schoolId: "sch-a",
    claimId: "clm-water",
    source: "headmaster",
    actorLabel: "Headmaster",
    value: "Available: Yes",
    timestamp: "2026-08-20T08:20:00",
    note: "Morning report",
  },
  {
    id: "sig-2",
    schoolId: "sch-a",
    claimId: "clm-water",
    source: "student-pulse",
    actorLabel: "Student sample (13/17)",
    value: "Available: No",
    timestamp: "2026-08-20T11:34:00",
    privacyProtected: true,
    note: "76% of sampled students reported no drinking water",
  },
  {
    id: "sig-3",
    schoolId: "sch-a",
    claimId: "clm-water",
    source: "student-report",
    actorLabel: "Anonymous student",
    value: "Reported: No drinking water",
    timestamp: "2026-08-19T10:02:00",
    privacyProtected: true,
    evidence: "Issue report #IR-208",
  },
  {
    id: "sig-4",
    schoolId: "sch-a",
    claimId: "clm-water",
    source: "headmaster",
    actorLabel: "Headmaster",
    value: "Cause: Pump failure",
    timestamp: "2026-08-18T15:40:00",
    note: "Confirms malfunction, reports funding dependency",
  },
  {
    id: "sig-5",
    schoolId: "sch-a",
    claimId: "clm-attendance",
    source: "teacher",
    actorLabel: "Teacher (Class 5)",
    value: "38 / 40 present",
    timestamp: "2026-08-20T09:05:00",
  },
  {
    id: "sig-6",
    schoolId: "sch-a",
    claimId: "clm-attendance",
    source: "student-report",
    actorLabel: "Student record checks",
    value: "7 marked present dispute record",
    timestamp: "2026-08-20T12:15:00",
    privacyProtected: true,
  },
  {
    id: "sig-7",
    schoolId: "sch-a",
    claimId: "clm-meal",
    source: "student-pulse",
    actorLabel: "Student sample (15/16)",
    value: "Meal served: Yes",
    timestamp: "2026-08-20T13:10:00",
    privacyProtected: true,
  },
  {
    id: "sig-8",
    schoolId: "sch-a",
    claimId: "clm-lab",
    source: "system",
    actorLabel: "System activity monitor",
    value: "Device activity: 0 in 31 days",
    timestamp: "2026-08-19T00:00:00",
  },
]

export const issues: Issue[] = [
  {
    id: "IS-101",
    schoolId: "sch-a",
    title: "Drinking water unavailable",
    domain: "Infrastructure",
    severity: "critical",
    confidence: "high",
    studentImpact: 184,
    firstDetected: "Aug 12",
    status: "escalated",
    responsibleLevel: "Block Authority",
    owner: "Biswan Block Office",
    dependency: "Pump replacement funding",
    deadline: "Aug 22",
    escalationLevel: 2,
    description:
      "Independently reported unavailable on 9 of the previous 12 instructional days. Headmaster confirmed pump failure; repair blocked by funding. Responsibility moved from school to block level.",
  },
  {
    id: "IS-102",
    schoolId: "sch-a",
    title: "Girls' toilet door broken",
    domain: "Infrastructure",
    severity: "medium",
    confidence: "medium",
    studentImpact: 88,
    firstDetected: "Aug 3",
    status: "in-progress",
    responsibleLevel: "Headmaster",
    owner: "Headmaster",
    dependency: "Local maintenance",
    deadline: "Aug 24",
    escalationLevel: 0,
    description: "Affects student access. Local maintenance requested and in progress.",
  },
  {
    id: "IS-103",
    schoolId: "sch-a",
    title: "Persistent attendance discrepancy",
    domain: "Students",
    severity: "medium",
    confidence: "medium",
    studentImpact: 40,
    firstDetected: "Aug 17",
    status: "under-review",
    responsibleLevel: "Headmaster",
    owner: "Headmaster",
    deadline: "Aug 23",
    escalationLevel: 0,
    description:
      "Reported attendance consistently exceeds independent student evidence. System requests clarification — not an accusation of misconduct.",
  },
  {
    id: "IS-104",
    schoolId: "sch-a",
    title: "Computer lab inactivity",
    domain: "Resources",
    severity: "low",
    confidence: "low",
    studentImpact: 60,
    firstDetected: "Aug 15",
    status: "action-required",
    responsibleLevel: "Cluster Authority",
    owner: "Rampur Cluster",
    dependency: "Physical verification",
    deadline: "Aug 28",
    escalationLevel: 0,
    description: "Reported functional but no device activity for 31 days. Verification requested.",
  },
]

export const waterTimeline: TimelineEvent[] = [
  { id: "t1", date: "Aug 1", source: "headmaster", text: "School reports drinking water functional.", kind: "report" },
  { id: "t2", date: "Aug 3", source: "student-pulse", text: "8 / 11 sampled students report no water.", kind: "report" },
  { id: "t3", date: "Aug 4", source: "student-pulse", text: "12 / 15 sampled students report no water.", kind: "report" },
  { id: "t4", date: "Aug 5", source: "headmaster", text: "Headmaster confirms pump malfunction.", kind: "evidence" },
  { id: "t5", date: "Aug 6", source: "system", text: "AI creates corrective action, assigns to headmaster.", kind: "action" },
  { id: "t6", date: "Aug 10", source: "headmaster", text: "Repair incomplete — funding dependency reported.", kind: "report" },
  { id: "t7", date: "Aug 15", source: "system", text: "Persistent unresolved issue — escalated to Block Authority.", kind: "escalation" },
  { id: "t8", date: "Aug 20", source: "student-pulse", text: "13 / 17 sampled students still report no water.", kind: "report" },
]

export const weeklyReviews: WeeklyReview[] = [
  {
    schoolId: "sch-a",
    weekLabel: "Week of Aug 17 – Aug 23",
    status: "escalated",
    headline:
      "Drinking water failure has persisted for 3 weeks and now sits with the Block Authority pending funding. Attendance reporting reliability continues to diverge from student evidence.",
    improved: [
      { label: "Midday meal service", detail: "Independently confirmed served on 5 of 5 days." },
      { label: "Student participation", detail: "Daily Pulse response rate rose from 61% to 78%." },
    ],
    deteriorated: [
      { label: "Water access", detail: "Unavailable on 9 of the last 12 instructional days." },
      { label: "Attendance reliability", detail: "Reality Gap widened to ~14 points." },
    ],
    observations: [
      "Student and staff reports on drinking water have conflicted for 4 consecutive days.",
      "Computer lab reported functional shows zero device activity for 31 days.",
    ],
    actionsDue: [
      { title: "Water pump replacement", owner: "Biswan Block Office", due: "Aug 22", status: "Escalated" },
      { title: "Girls' toilet repair", owner: "Headmaster", due: "Aug 24", status: "In progress" },
      { title: "Attendance clarification", owner: "Headmaster", due: "Aug 23", status: "Awaiting response" },
    ],
    escalations: ["IS-101 Drinking water — persistent unresolved (Block level, day 8)."],
    confidenceNotes: [
      "Computer lab status: Low confidence — last inspection 8 months ago.",
      "Attendance: Medium confidence — awaiting teacher clarification.",
    ],
  },
]

export const schoolMemory: MemoryEvent[] = [
  { year: "2024", text: "Water pump failure → repaired (local maintenance)." },
  { year: "2025", text: "Water pump failure → repaired (local maintenance)." },
  { year: "2026 (Feb)", text: "Water pump failure → repaired (local maintenance)." },
  { year: "2026 (Aug)", text: "Water pump failure recurring — repairs appear temporary." },
]

export const memoryInsight =
  "This is the 4th pump-related failure in 31 months. Previous repairs appear temporary. Replacement should be evaluated instead of another repair."

export const pulseQuestions: PulseQuestion[] = [
  { id: "pq-1", text: "Were you at school today?", claimId: "clm-attendance" },
  { id: "pq-2", text: "Was drinking water available today?", claimId: "clm-water" },
  { id: "pq-3", text: "Did your mathematics class happen?", claimId: "clm-teacher" },
  { id: "pq-4", text: "Was the midday meal served?", claimId: "clm-meal" },
  { id: "pq-5", text: "Could you use the toilet today?", claimId: "clm-toilet" },
]

export const studentAttendance: AttendanceRecord[] = [
  { date: "Mon, Aug 17", status: "present" },
  { date: "Tue, Aug 18", status: "present" },
  { date: "Wed, Aug 19", status: "absent" },
  { date: "Thu, Aug 20", status: "present" },
]

export const studentEntitlements = [
  { id: "ent-1", label: "Textbook set (Class 5)", status: "confirmed" as const },
  { id: "ent-2", label: "School uniform", status: "confirmed" as const },
  { id: "ent-3", label: "Midday meal today", status: "pending" as const },
]

export const attendanceTrend: TrendPoint[] = [
  { label: "W1", reported: 95, observed: 93 },
  { label: "W2", reported: 96, observed: 90 },
  { label: "W3", reported: 96, observed: 86 },
  { label: "W4", reported: 95, observed: 84 },
  { label: "W5", reported: 96, observed: 83 },
  { label: "Now", reported: 96, observed: 82 },
]

export const issueCategories = [
  "No drinking water",
  "Toilet unusable",
  "Classroom damage",
  "Meal not served",
  "Teacher repeatedly absent",
  "Classes repeatedly not happening",
  "School unexpectedly closed",
  "Unsafe infrastructure",
  "Other",
]

export interface AskAnswer {
  q: string
  a: string
  evidence: string[]
}

export const askSuggestions: AskAnswer[] = [
  {
    q: "Which school needs my attention most?",
    a: "Govt Primary School, Rampur is the highest priority. Drinking water has been unavailable for 11 instructional days affecting 184 students, confidence is High, and a previously assigned action is overdue.",
    evidence: [
      "Priority score: Severity (critical) × Duration (11 days) × Impact (184) × Confidence (high)",
      "IS-101 escalated to Block Authority on Aug 15, still unresolved",
      "13/17 sampled students confirmed no water on Aug 20",
    ],
  },
  {
    q: "Why was Rampur escalated?",
    a: "Rampur was escalated because the drinking water issue met the policy threshold: high severity, persistent duration beyond 7 days, high student impact, and a resolution dependency (funding) outside the school's control. The system escalated the problem, not the headmaster.",
    evidence: [
      "Detect (Aug 3) → Assist (Aug 5) → Assign (Aug 6) → funding dependency (Aug 10) → Escalate (Aug 15)",
      "Responsibility reassigned from Headmaster to Block Authority",
    ],
  },
  {
    q: "Which schools have unresolved sanitation problems for over two weeks?",
    a: "One school currently qualifies: Rampur (girls' toilet door broken since Aug 3, and drinking water since Aug 12). Mahmudabad has a toilet-cleaning complaint opened 6 days ago — below the two-week threshold.",
    evidence: ["IS-101 open 8 days", "IS-102 open 17 days", "Mahmudabad complaint open 6 days"],
  },
  {
    q: "Which schools have persistent attendance Reality Gaps?",
    a: "Rampur shows a persistent gap (reported 96% vs observed ~82%). Reusa shows a widening minor gap (89% vs 84%). Both are flagged for clarification rather than misconduct.",
    evidence: ["Rampur gap ~14 pts over 5 weeks", "Reusa gap ~5 pts, first appeared this week"],
  },
]
